#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Trail_Tracker.Resource", IsApplication=true)]

namespace Trail_Tracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0b0000
			public const int planets_array = 2131427328;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010024
			public const int font = 2130772004;
			
			// aapt resource value: 0x7f01001d
			public const int fontProviderAuthority = 2130771997;
			
			// aapt resource value: 0x7f010020
			public const int fontProviderCerts = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int fontProviderFetchStrategy = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int fontProviderFetchTimeout = 2130772002;
			
			// aapt resource value: 0x7f01001e
			public const int fontProviderPackage = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int fontProviderQuery = 2130771999;
			
			// aapt resource value: 0x7f010023
			public const int fontStyle = 2130772003;
			
			// aapt resource value: 0x7f010025
			public const int fontWeight = 2130772005;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int abc_action_bar_embed_tabs = 2131230720;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06001a
			public const int aqua = 2131099674;
			
			// aapt resource value: 0x7f060020
			public const int black = 2131099680;
			
			// aapt resource value: 0x7f06001e
			public const int blue = 2131099678;
			
			// aapt resource value: 0x7f060022
			public const int common_google_signin_btn_text_dark = 2131099682;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f060023
			public const int common_google_signin_btn_text_light = 2131099683;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			// aapt resource value: 0x7f060024
			public const int common_google_signin_btn_tint = 2131099684;
			
			// aapt resource value: 0x7f060021
			public const int dark_grey = 2131099681;
			
			// aapt resource value: 0x7f060013
			public const int fuchsia = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int green = 2131099677;
			
			// aapt resource value: 0x7f060016
			public const int grey = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int lime = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int maroon = 2131099673;
			
			// aapt resource value: 0x7f06001f
			public const int navy = 2131099679;
			
			// aapt resource value: 0x7f06000b
			public const int notification_action_color_filter = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int notification_icon_bg_color = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int notification_material_background_media_default_color = 2131099656;
			
			// aapt resource value: 0x7f060017
			public const int olive = 2131099671;
			
			// aapt resource value: 0x7f060009
			public const int primary_text_default_material_dark = 2131099657;
			
			// aapt resource value: 0x7f060018
			public const int purple = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int red = 2131099668;
			
			// aapt resource value: 0x7f06000d
			public const int ripple_material_light = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int secondary_text_default_material_dark = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int secondary_text_default_material_light = 2131099662;
			
			// aapt resource value: 0x7f060015
			public const int silver = 2131099669;
			
			// aapt resource value: 0x7f06001c
			public const int teal = 2131099676;
			
			// aapt resource value: 0x7f060010
			public const int theme_blue = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int theme_green = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int white = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int yellow = 2131099666;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090004
			public const int compat_button_inset_horizontal_material = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int compat_button_inset_vertical_material = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int compat_button_padding_horizontal_material = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int compat_button_padding_vertical_material = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int compat_control_corner_material = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int notification_action_icon_size = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int notification_action_text_size = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int notification_big_circle_margin = 2131296267;
			
			// aapt resource value: 0x7f090001
			public const int notification_content_margin_start = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int notification_large_icon_height = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int notification_large_icon_width = 2131296269;
			
			// aapt resource value: 0x7f090002
			public const int notification_main_column_padding_top = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int notification_media_narrow_margin = 2131296259;
			
			// aapt resource value: 0x7f09000e
			public const int notification_right_icon_size = 2131296270;
			
			// aapt resource value: 0x7f090000
			public const int notification_right_side_padding_top = 2131296256;
			
			// aapt resource value: 0x7f09000f
			public const int notification_small_icon_background_padding = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int notification_small_icon_size_as_large = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int notification_subtext_size = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int notification_top_pad = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int notification_top_pad_large_text = 2131296275;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AddButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blue_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_full_open_on_phone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_focused = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_focused = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_normal_background = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_normal_background = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_disabled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_normal_background = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int googleg_disabled_color_18 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int googleg_standard_color_18 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Icon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int notification_action_background = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int notification_bg = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int notification_bg_low = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_bg_low_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_bg_low_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int notification_bg_normal = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int notification_bg_normal_pressed = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notification_icon_background = 2130837535;
			
			// aapt resource value: 0x7f020024
			public const int notification_template_icon_bg = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int notification_template_icon_low_bg = 2130837541;
			
			// aapt resource value: 0x7f020020
			public const int notification_tile_bg = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notify_panel_notification_icon_bg = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Pin = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int TrailTrackerIcon = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0033
			public const int action0 = 2131361843;
			
			// aapt resource value: 0x7f0a0030
			public const int action_container = 2131361840;
			
			// aapt resource value: 0x7f0a0037
			public const int action_divider = 2131361847;
			
			// aapt resource value: 0x7f0a0031
			public const int action_image = 2131361841;
			
			// aapt resource value: 0x7f0a0032
			public const int action_text = 2131361842;
			
			// aapt resource value: 0x7f0a0041
			public const int actions = 2131361857;
			
			// aapt resource value: 0x7f0a000a
			public const int adjust_height = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int adjust_width = 2131361803;
			
			// aapt resource value: 0x7f0a0012
			public const int async = 2131361810;
			
			// aapt resource value: 0x7f0a000f
			public const int auto = 2131361807;
			
			// aapt resource value: 0x7f0a0013
			public const int blocking = 2131361811;
			
			// aapt resource value: 0x7f0a001d
			public const int btnAddFriends = 2131361821;
			
			// aapt resource value: 0x7f0a002c
			public const int btnAddTrail = 2131361836;
			
			// aapt resource value: 0x7f0a001c
			public const int btnCancelAddFriends = 2131361820;
			
			// aapt resource value: 0x7f0a0018
			public const int btnCheckPasswordDialogCancel = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int btnCheckPasswordDialogConfirm = 2131361817;
			
			// aapt resource value: 0x7f0a0056
			public const int btnConfirmSignUp = 2131361878;
			
			// aapt resource value: 0x7f0a002e
			public const int btnFriends = 2131361838;
			
			// aapt resource value: 0x7f0a002d
			public const int btnLikedTrails = 2131361837;
			
			// aapt resource value: 0x7f0a0020
			public const int btnLikedTrailsDialogCancel = 2131361824;
			
			// aapt resource value: 0x7f0a002b
			public const int btnSearchTrail = 2131361835;
			
			// aapt resource value: 0x7f0a002f
			public const int btnSettings = 2131361839;
			
			// aapt resource value: 0x7f0a004d
			public const int btnSettingsDialogCancel = 2131361869;
			
			// aapt resource value: 0x7f0a0022
			public const int btnSignIn = 2131361826;
			
			// aapt resource value: 0x7f0a0024
			public const int btnSignUp = 2131361828;
			
			// aapt resource value: 0x7f0a0058
			public const int btnTracking = 2131361880;
			
			// aapt resource value: 0x7f0a005c
			public const int btnTrackingCancel = 2131361884;
			
			// aapt resource value: 0x7f0a0062
			public const int btnTrailInfoDislike = 2131361890;
			
			// aapt resource value: 0x7f0a0060
			public const int btnTrailInfoLike = 2131361888;
			
			// aapt resource value: 0x7f0a0065
			public const int btnTrailSearchDialogCancel = 2131361893;
			
			// aapt resource value: 0x7f0a0066
			public const int btnTrailSearchDialogConfirm = 2131361894;
			
			// aapt resource value: 0x7f0a006b
			public const int btnTrailSubmitDialogCancel = 2131361899;
			
			// aapt resource value: 0x7f0a006c
			public const int btnTrailSubmitDialogConfirm = 2131361900;
			
			// aapt resource value: 0x7f0a0049
			public const int btnUpdateEmail = 2131361865;
			
			// aapt resource value: 0x7f0a004c
			public const int btnUpdatePassword = 2131361868;
			
			// aapt resource value: 0x7f0a0046
			public const int btnUpdateUsername = 2131361862;
			
			// aapt resource value: 0x7f0a006e
			public const int btnUserSearchDialogCancel = 2131361902;
			
			// aapt resource value: 0x7f0a006f
			public const int btnUserSearchDialogConfirm = 2131361903;
			
			// aapt resource value: 0x7f0a0029
			public const int buttonlogin = 2131361833;
			
			// aapt resource value: 0x7f0a0034
			public const int cancel_action = 2131361844;
			
			// aapt resource value: 0x7f0a003c
			public const int chronometer = 2131361852;
			
			// aapt resource value: 0x7f0a0010
			public const int dark = 2131361808;
			
			// aapt resource value: 0x7f0a0055
			public const int emailtext = 2131361877;
			
			// aapt resource value: 0x7f0a0043
			public const int end_padder = 2131361859;
			
			// aapt resource value: 0x7f0a0014
			public const int forever = 2131361812;
			
			// aapt resource value: 0x7f0a0005
			public const int hybrid = 2131361797;
			
			// aapt resource value: 0x7f0a003e
			public const int icon = 2131361854;
			
			// aapt resource value: 0x7f0a0042
			public const int icon_group = 2131361858;
			
			// aapt resource value: 0x7f0a000c
			public const int icon_only = 2131361804;
			
			// aapt resource value: 0x7f0a003d
			public const int info = 2131361853;
			
			// aapt resource value: 0x7f0a0015
			public const int italic = 2131361813;
			
			// aapt resource value: 0x7f0a0011
			public const int light = 2131361809;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a001b
			public const int lvFriends = 2131361819;
			
			// aapt resource value: 0x7f0a001f
			public const int lvLikedTrails = 2131361823;
			
			// aapt resource value: 0x7f0a0067
			public const int lvTrailSearchDialog = 2131361895;
			
			// aapt resource value: 0x7f0a0070
			public const int lvUserSearchDialog = 2131361904;
			
			// aapt resource value: 0x7f0a002a
			public const int map = 2131361834;
			
			// aapt resource value: 0x7f0a0036
			public const int media_actions = 2131361846;
			
			// aapt resource value: 0x7f0a0006
			public const int none = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int normal = 2131361799;
			
			// aapt resource value: 0x7f0a0040
			public const int notification_background = 2131361856;
			
			// aapt resource value: 0x7f0a0039
			public const int notification_main_column = 2131361849;
			
			// aapt resource value: 0x7f0a0038
			public const int notification_main_column_container = 2131361848;
			
			// aapt resource value: 0x7f0a0051
			public const int passwordtext = 2131361873;
			
			// aapt resource value: 0x7f0a0053
			public const int repeatpasswordtext = 2131361875;
			
			// aapt resource value: 0x7f0a003f
			public const int right_icon = 2131361855;
			
			// aapt resource value: 0x7f0a003a
			public const int right_side = 2131361850;
			
			// aapt resource value: 0x7f0a0008
			public const int satellite = 2131361800;
			
			// aapt resource value: 0x7f0a0028
			public const int signinpassword = 2131361832;
			
			// aapt resource value: 0x7f0a0026
			public const int signinusername = 2131361830;
			
			// aapt resource value: 0x7f0a000d
			public const int standard = 2131361805;
			
			// aapt resource value: 0x7f0a0035
			public const int status_bar_latest_event_content = 2131361845;
			
			// aapt resource value: 0x7f0a0009
			public const int terrain = 2131361801;
			
			// aapt resource value: 0x7f0a0002
			public const int text = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text2 = 2131361795;
			
			// aapt resource value: 0x7f0a0021
			public const int textCreateAccount = 2131361825;
			
			// aapt resource value: 0x7f0a0047
			public const int textEmail = 2131361863;
			
			// aapt resource value: 0x7f0a0023
			public const int textOR = 2131361827;
			
			// aapt resource value: 0x7f0a004a
			public const int textPassword = 2131361866;
			
			// aapt resource value: 0x7f0a0016
			public const int textTrailSearchDialogHeader = 2131361814;
			
			// aapt resource value: 0x7f0a0068
			public const int textTrailSubmitDialogHeader = 2131361896;
			
			// aapt resource value: 0x7f0a0057
			public const int textTrailTrackerHeader = 2131361879;
			
			// aapt resource value: 0x7f0a0044
			public const int textUsername = 2131361860;
			
			// aapt resource value: 0x7f0a0052
			public const int textconfirmpassword = 2131361874;
			
			// aapt resource value: 0x7f0a0054
			public const int textemail = 2131361876;
			
			// aapt resource value: 0x7f0a0050
			public const int textpassword = 2131361872;
			
			// aapt resource value: 0x7f0a004e
			public const int textusername = 2131361870;
			
			// aapt resource value: 0x7f0a0027
			public const int textviewpassword = 2131361831;
			
			// aapt resource value: 0x7f0a0025
			public const int textviewusername = 2131361829;
			
			// aapt resource value: 0x7f0a003b
			public const int time = 2131361851;
			
			// aapt resource value: 0x7f0a0004
			public const int title = 2131361796;
			
			// aapt resource value: 0x7f0a005b
			public const int txtDistance = 2131361883;
			
			// aapt resource value: 0x7f0a001a
			public const int txtFriendsDialogHeader = 2131361818;
			
			// aapt resource value: 0x7f0a0059
			public const int txtLatitude = 2131361881;
			
			// aapt resource value: 0x7f0a001e
			public const int txtLikedTrailsDialogHeader = 2131361822;
			
			// aapt resource value: 0x7f0a005a
			public const int txtLongitude = 2131361882;
			
			// aapt resource value: 0x7f0a0063
			public const int txtTrailDislikes = 2131361891;
			
			// aapt resource value: 0x7f0a005e
			public const int txtTrailLength = 2131361886;
			
			// aapt resource value: 0x7f0a0061
			public const int txtTrailLikes = 2131361889;
			
			// aapt resource value: 0x7f0a005d
			public const int txtTrailName = 2131361885;
			
			// aapt resource value: 0x7f0a006a
			public const int txtTrailSubmitDialogLength = 2131361898;
			
			// aapt resource value: 0x7f0a005f
			public const int txtTrailUsername = 2131361887;
			
			// aapt resource value: 0x7f0a0017
			public const int txtboxCheckPassword = 2131361815;
			
			// aapt resource value: 0x7f0a0069
			public const int txtboxTrailName = 2131361897;
			
			// aapt resource value: 0x7f0a0064
			public const int txtboxTrailSearch = 2131361892;
			
			// aapt resource value: 0x7f0a0048
			public const int txtboxUpdateEmail = 2131361864;
			
			// aapt resource value: 0x7f0a004b
			public const int txtboxUpdatePassword = 2131361867;
			
			// aapt resource value: 0x7f0a0045
			public const int txtboxUpdateUsername = 2131361861;
			
			// aapt resource value: 0x7f0a006d
			public const int txtboxUserSearch = 2131361901;
			
			// aapt resource value: 0x7f0a004f
			public const int usernametext = 2131361871;
			
			// aapt resource value: 0x7f0a000e
			public const int wide = 2131361806;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040001
			public const int cancel_button_image_alpha = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int status_bar_notification_info_maxnum = 2130968578;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CheckPasswordDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FriendsDialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LikedTrailsDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LoginDialog = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Map = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_action = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_action_tombstone = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_media_action = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_media_cancel_action = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_big_media = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_big_media_custom = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_big_media_narrow = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_big_media_narrow_custom = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_custom_big = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_icon_group = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_lines_media = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_media = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int notification_template_media_custom = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int notification_template_part_chronometer = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int notification_template_part_time = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int SettingsDialog = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int SignUpDialog = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Tracking = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int TrailInfoDialog = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int TrailSearchDialog = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int TrailSubmitDialog = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int UserSearchDialog = 2130903067;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050012
			public const int app_name = 2131034130;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_button = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_enable_title = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_install_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_notification_ticker = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_unknown_issue = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_unsupported_text = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_button = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_update_title = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_wear_update_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_open_on_phone = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_signin_button_text_long = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int default_web_client_id = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int firebase_database_url = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int gcm_defaultSenderId = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int google_api_key = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int google_app_id = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int google_storage_bucket = 2131034138;
			
			// aapt resource value: 0x7f050013
			public const int rating_spinner = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int status_bar_notification_info_overflow = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int url = 2131034132;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f07000c
			public const int MyTheme = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int TextAppearance_Compat_Notification = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int TextAppearance_Compat_Notification_Info = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int TextAppearance_Compat_Notification_Media = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int TextAppearance_Compat_Notification_Time = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int TextAppearance_Compat_Notification_Title = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int ToolBarStyle = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int Widget_Compat_NotificationActionContainer = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int Widget_Compat_NotificationActionText = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int button_text = 2131165198;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130772003,
					2130772004,
					2130772005};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
